run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
  uniq-by-line: false

linters:
  enable:
    - containedctx
    - contextcheck
    - dogsled
    - errcheck
    - errorlint
    - gci
    - gosec
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mnd
    - nilerr
    - nilnil
    - paralleltest
    - protogetter
    - revive
    - sloglint
    - staticcheck
    - unused
    - wsl

linters-settings:
  paralleltest:
    ignore-missing: false

  sloglint:
    kv-only: true
    key-naming-case: snake

  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(github.com/linode)
