apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: example-class
driverName: objectstorage.cosi.linode.com
deletionPolicy: Delete
parameters:
  cosi.linode.com/v1/region: us-east-1
  cosi.linode.com/v1/acl: private
  cosi.linode.com/v1/cors: disabled
