apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      otlp/jaeger:
        endpoint: "simplest-collector.observability:4317"

      prometheus:
        endpoint: "0.0.0.0:8080"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
