// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/linodeclient/linodeclient.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/linodeclient/linodeclient.go -destination=./testing/mock/linodeclient.gen.go -package=mock -typed -mock_names=Client=MockLinodeClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	linodego "github.com/linode/linodego"
	gomock "go.uber.org/mock/gomock"
)

// MockLinodeClient is a mock of Client interface.
type MockLinodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeClientMockRecorder
	isgomock struct{}
}

// MockLinodeClientMockRecorder is the mock recorder for MockLinodeClient.
type MockLinodeClientMockRecorder struct {
	mock *MockLinodeClient
}

// NewMockLinodeClient creates a new mock instance.
func NewMockLinodeClient(ctrl *gomock.Controller) *MockLinodeClient {
	mock := &MockLinodeClient{ctrl: ctrl}
	mock.recorder = &MockLinodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeClient) EXPECT() *MockLinodeClientMockRecorder {
	return m.recorder
}

// CreateObjectStorageBucket mocks base method.
func (m *MockLinodeClient) CreateObjectStorageBucket(arg0 context.Context, arg1 linodego.ObjectStorageBucketCreateOptions) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageBucket", arg0, arg1)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageBucket indicates an expected call of CreateObjectStorageBucket.
func (mr *MockLinodeClientMockRecorder) CreateObjectStorageBucket(arg0, arg1 any) *MockLinodeClientCreateObjectStorageBucketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageBucket", reflect.TypeOf((*MockLinodeClient)(nil).CreateObjectStorageBucket), arg0, arg1)
	return &MockLinodeClientCreateObjectStorageBucketCall{Call: call}
}

// MockLinodeClientCreateObjectStorageBucketCall wrap *gomock.Call
type MockLinodeClientCreateObjectStorageBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientCreateObjectStorageBucketCall) Return(arg0 *linodego.ObjectStorageBucket, arg1 error) *MockLinodeClientCreateObjectStorageBucketCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientCreateObjectStorageBucketCall) Do(f func(context.Context, linodego.ObjectStorageBucketCreateOptions) (*linodego.ObjectStorageBucket, error)) *MockLinodeClientCreateObjectStorageBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientCreateObjectStorageBucketCall) DoAndReturn(f func(context.Context, linodego.ObjectStorageBucketCreateOptions) (*linodego.ObjectStorageBucket, error)) *MockLinodeClientCreateObjectStorageBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateObjectStorageKey mocks base method.
func (m *MockLinodeClient) CreateObjectStorageKey(arg0 context.Context, arg1 linodego.ObjectStorageKeyCreateOptions) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageKey", arg0, arg1)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageKey indicates an expected call of CreateObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) CreateObjectStorageKey(arg0, arg1 any) *MockLinodeClientCreateObjectStorageKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).CreateObjectStorageKey), arg0, arg1)
	return &MockLinodeClientCreateObjectStorageKeyCall{Call: call}
}

// MockLinodeClientCreateObjectStorageKeyCall wrap *gomock.Call
type MockLinodeClientCreateObjectStorageKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientCreateObjectStorageKeyCall) Return(arg0 *linodego.ObjectStorageKey, arg1 error) *MockLinodeClientCreateObjectStorageKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientCreateObjectStorageKeyCall) Do(f func(context.Context, linodego.ObjectStorageKeyCreateOptions) (*linodego.ObjectStorageKey, error)) *MockLinodeClientCreateObjectStorageKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientCreateObjectStorageKeyCall) DoAndReturn(f func(context.Context, linodego.ObjectStorageKeyCreateOptions) (*linodego.ObjectStorageKey, error)) *MockLinodeClientCreateObjectStorageKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteObjectStorageBucket mocks base method.
func (m *MockLinodeClient) DeleteObjectStorageBucket(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStorageBucket", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStorageBucket indicates an expected call of DeleteObjectStorageBucket.
func (mr *MockLinodeClientMockRecorder) DeleteObjectStorageBucket(arg0, arg1, arg2 any) *MockLinodeClientDeleteObjectStorageBucketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStorageBucket", reflect.TypeOf((*MockLinodeClient)(nil).DeleteObjectStorageBucket), arg0, arg1, arg2)
	return &MockLinodeClientDeleteObjectStorageBucketCall{Call: call}
}

// MockLinodeClientDeleteObjectStorageBucketCall wrap *gomock.Call
type MockLinodeClientDeleteObjectStorageBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientDeleteObjectStorageBucketCall) Return(arg0 error) *MockLinodeClientDeleteObjectStorageBucketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientDeleteObjectStorageBucketCall) Do(f func(context.Context, string, string) error) *MockLinodeClientDeleteObjectStorageBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientDeleteObjectStorageBucketCall) DoAndReturn(f func(context.Context, string, string) error) *MockLinodeClientDeleteObjectStorageBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteObjectStorageKey mocks base method.
func (m *MockLinodeClient) DeleteObjectStorageKey(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStorageKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStorageKey indicates an expected call of DeleteObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) DeleteObjectStorageKey(arg0, arg1 any) *MockLinodeClientDeleteObjectStorageKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).DeleteObjectStorageKey), arg0, arg1)
	return &MockLinodeClientDeleteObjectStorageKeyCall{Call: call}
}

// MockLinodeClientDeleteObjectStorageKeyCall wrap *gomock.Call
type MockLinodeClientDeleteObjectStorageKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientDeleteObjectStorageKeyCall) Return(arg0 error) *MockLinodeClientDeleteObjectStorageKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientDeleteObjectStorageKeyCall) Do(f func(context.Context, int) error) *MockLinodeClientDeleteObjectStorageKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientDeleteObjectStorageKeyCall) DoAndReturn(f func(context.Context, int) error) *MockLinodeClientDeleteObjectStorageKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObjectStorageBucket mocks base method.
func (m *MockLinodeClient) GetObjectStorageBucket(arg0 context.Context, arg1, arg2 string) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageBucket", arg0, arg1, arg2)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageBucket indicates an expected call of GetObjectStorageBucket.
func (mr *MockLinodeClientMockRecorder) GetObjectStorageBucket(arg0, arg1, arg2 any) *MockLinodeClientGetObjectStorageBucketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageBucket", reflect.TypeOf((*MockLinodeClient)(nil).GetObjectStorageBucket), arg0, arg1, arg2)
	return &MockLinodeClientGetObjectStorageBucketCall{Call: call}
}

// MockLinodeClientGetObjectStorageBucketCall wrap *gomock.Call
type MockLinodeClientGetObjectStorageBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientGetObjectStorageBucketCall) Return(arg0 *linodego.ObjectStorageBucket, arg1 error) *MockLinodeClientGetObjectStorageBucketCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientGetObjectStorageBucketCall) Do(f func(context.Context, string, string) (*linodego.ObjectStorageBucket, error)) *MockLinodeClientGetObjectStorageBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientGetObjectStorageBucketCall) DoAndReturn(f func(context.Context, string, string) (*linodego.ObjectStorageBucket, error)) *MockLinodeClientGetObjectStorageBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObjectStorageBucketAccess mocks base method.
func (m *MockLinodeClient) GetObjectStorageBucketAccess(arg0 context.Context, arg1, arg2 string) (*linodego.ObjectStorageBucketAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageBucketAccess", arg0, arg1, arg2)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucketAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageBucketAccess indicates an expected call of GetObjectStorageBucketAccess.
func (mr *MockLinodeClientMockRecorder) GetObjectStorageBucketAccess(arg0, arg1, arg2 any) *MockLinodeClientGetObjectStorageBucketAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageBucketAccess", reflect.TypeOf((*MockLinodeClient)(nil).GetObjectStorageBucketAccess), arg0, arg1, arg2)
	return &MockLinodeClientGetObjectStorageBucketAccessCall{Call: call}
}

// MockLinodeClientGetObjectStorageBucketAccessCall wrap *gomock.Call
type MockLinodeClientGetObjectStorageBucketAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientGetObjectStorageBucketAccessCall) Return(arg0 *linodego.ObjectStorageBucketAccess, arg1 error) *MockLinodeClientGetObjectStorageBucketAccessCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientGetObjectStorageBucketAccessCall) Do(f func(context.Context, string, string) (*linodego.ObjectStorageBucketAccess, error)) *MockLinodeClientGetObjectStorageBucketAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientGetObjectStorageBucketAccessCall) DoAndReturn(f func(context.Context, string, string) (*linodego.ObjectStorageBucketAccess, error)) *MockLinodeClientGetObjectStorageBucketAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObjectStorageKey mocks base method.
func (m *MockLinodeClient) GetObjectStorageKey(arg0 context.Context, arg1 int) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageKey", arg0, arg1)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageKey indicates an expected call of GetObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) GetObjectStorageKey(arg0, arg1 any) *MockLinodeClientGetObjectStorageKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).GetObjectStorageKey), arg0, arg1)
	return &MockLinodeClientGetObjectStorageKeyCall{Call: call}
}

// MockLinodeClientGetObjectStorageKeyCall wrap *gomock.Call
type MockLinodeClientGetObjectStorageKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientGetObjectStorageKeyCall) Return(arg0 *linodego.ObjectStorageKey, arg1 error) *MockLinodeClientGetObjectStorageKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientGetObjectStorageKeyCall) Do(f func(context.Context, int) (*linodego.ObjectStorageKey, error)) *MockLinodeClientGetObjectStorageKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientGetObjectStorageKeyCall) DoAndReturn(f func(context.Context, int) (*linodego.ObjectStorageKey, error)) *MockLinodeClientGetObjectStorageKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListObjectStorageEndpoints mocks base method.
func (m *MockLinodeClient) ListObjectStorageEndpoints(arg0 context.Context, arg1 *linodego.ListOptions) ([]linodego.ObjectStorageEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectStorageEndpoints", arg0, arg1)
	ret0, _ := ret[0].([]linodego.ObjectStorageEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectStorageEndpoints indicates an expected call of ListObjectStorageEndpoints.
func (mr *MockLinodeClientMockRecorder) ListObjectStorageEndpoints(arg0, arg1 any) *MockLinodeClientListObjectStorageEndpointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectStorageEndpoints", reflect.TypeOf((*MockLinodeClient)(nil).ListObjectStorageEndpoints), arg0, arg1)
	return &MockLinodeClientListObjectStorageEndpointsCall{Call: call}
}

// MockLinodeClientListObjectStorageEndpointsCall wrap *gomock.Call
type MockLinodeClientListObjectStorageEndpointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientListObjectStorageEndpointsCall) Return(arg0 []linodego.ObjectStorageEndpoint, arg1 error) *MockLinodeClientListObjectStorageEndpointsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientListObjectStorageEndpointsCall) Do(f func(context.Context, *linodego.ListOptions) ([]linodego.ObjectStorageEndpoint, error)) *MockLinodeClientListObjectStorageEndpointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientListObjectStorageEndpointsCall) DoAndReturn(f func(context.Context, *linodego.ListOptions) ([]linodego.ObjectStorageEndpoint, error)) *MockLinodeClientListObjectStorageEndpointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListObjectStorageKeys mocks base method.
func (m *MockLinodeClient) ListObjectStorageKeys(arg0 context.Context, arg1 *linodego.ListOptions) ([]linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectStorageKeys", arg0, arg1)
	ret0, _ := ret[0].([]linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectStorageKeys indicates an expected call of ListObjectStorageKeys.
func (mr *MockLinodeClientMockRecorder) ListObjectStorageKeys(arg0, arg1 any) *MockLinodeClientListObjectStorageKeysCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectStorageKeys", reflect.TypeOf((*MockLinodeClient)(nil).ListObjectStorageKeys), arg0, arg1)
	return &MockLinodeClientListObjectStorageKeysCall{Call: call}
}

// MockLinodeClientListObjectStorageKeysCall wrap *gomock.Call
type MockLinodeClientListObjectStorageKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientListObjectStorageKeysCall) Return(arg0 []linodego.ObjectStorageKey, arg1 error) *MockLinodeClientListObjectStorageKeysCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientListObjectStorageKeysCall) Do(f func(context.Context, *linodego.ListOptions) ([]linodego.ObjectStorageKey, error)) *MockLinodeClientListObjectStorageKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientListObjectStorageKeysCall) DoAndReturn(f func(context.Context, *linodego.ListOptions) ([]linodego.ObjectStorageKey, error)) *MockLinodeClientListObjectStorageKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateObjectStorageBucketAccess mocks base method.
func (m *MockLinodeClient) UpdateObjectStorageBucketAccess(arg0 context.Context, arg1, arg2 string, arg3 linodego.ObjectStorageBucketUpdateAccessOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjectStorageBucketAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjectStorageBucketAccess indicates an expected call of UpdateObjectStorageBucketAccess.
func (mr *MockLinodeClientMockRecorder) UpdateObjectStorageBucketAccess(arg0, arg1, arg2, arg3 any) *MockLinodeClientUpdateObjectStorageBucketAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjectStorageBucketAccess", reflect.TypeOf((*MockLinodeClient)(nil).UpdateObjectStorageBucketAccess), arg0, arg1, arg2, arg3)
	return &MockLinodeClientUpdateObjectStorageBucketAccessCall{Call: call}
}

// MockLinodeClientUpdateObjectStorageBucketAccessCall wrap *gomock.Call
type MockLinodeClientUpdateObjectStorageBucketAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinodeClientUpdateObjectStorageBucketAccessCall) Return(arg0 error) *MockLinodeClientUpdateObjectStorageBucketAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinodeClientUpdateObjectStorageBucketAccessCall) Do(f func(context.Context, string, string, linodego.ObjectStorageBucketUpdateAccessOptions) error) *MockLinodeClientUpdateObjectStorageBucketAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinodeClientUpdateObjectStorageBucketAccessCall) DoAndReturn(f func(context.Context, string, string, linodego.ObjectStorageBucketUpdateAccessOptions) error) *MockLinodeClientUpdateObjectStorageBucketAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
