// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/s3/s3.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/s3/s3.go -destination=./testing/mock/s3.gen.go -package=mock -typed -mock_names=Client=MockS3Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockS3Client is a mock of Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// GetBucketPolicy mocks base method.
func (m *MockS3Client) GetBucketPolicy(ctx context.Context, region, bucketName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketPolicy", ctx, region, bucketName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketPolicy indicates an expected call of GetBucketPolicy.
func (mr *MockS3ClientMockRecorder) GetBucketPolicy(ctx, region, bucketName any) *MockS3ClientGetBucketPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketPolicy", reflect.TypeOf((*MockS3Client)(nil).GetBucketPolicy), ctx, region, bucketName)
	return &MockS3ClientGetBucketPolicyCall{Call: call}
}

// MockS3ClientGetBucketPolicyCall wrap *gomock.Call
type MockS3ClientGetBucketPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockS3ClientGetBucketPolicyCall) Return(arg0 string, arg1 error) *MockS3ClientGetBucketPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockS3ClientGetBucketPolicyCall) Do(f func(context.Context, string, string) (string, error)) *MockS3ClientGetBucketPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockS3ClientGetBucketPolicyCall) DoAndReturn(f func(context.Context, string, string) (string, error)) *MockS3ClientGetBucketPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prune mocks base method.
func (m *MockS3Client) Prune(ctx context.Context, region, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, region, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune.
func (mr *MockS3ClientMockRecorder) Prune(ctx, region, bucket any) *MockS3ClientPruneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockS3Client)(nil).Prune), ctx, region, bucket)
	return &MockS3ClientPruneCall{Call: call}
}

// MockS3ClientPruneCall wrap *gomock.Call
type MockS3ClientPruneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockS3ClientPruneCall) Return(arg0 error) *MockS3ClientPruneCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockS3ClientPruneCall) Do(f func(context.Context, string, string) error) *MockS3ClientPruneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockS3ClientPruneCall) DoAndReturn(f func(context.Context, string, string) error) *MockS3ClientPruneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetBucketPolicy mocks base method.
func (m *MockS3Client) SetBucketPolicy(ctx context.Context, region, bucketName, policy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBucketPolicy", ctx, region, bucketName, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBucketPolicy indicates an expected call of SetBucketPolicy.
func (mr *MockS3ClientMockRecorder) SetBucketPolicy(ctx, region, bucketName, policy any) *MockS3ClientSetBucketPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBucketPolicy", reflect.TypeOf((*MockS3Client)(nil).SetBucketPolicy), ctx, region, bucketName, policy)
	return &MockS3ClientSetBucketPolicyCall{Call: call}
}

// MockS3ClientSetBucketPolicyCall wrap *gomock.Call
type MockS3ClientSetBucketPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockS3ClientSetBucketPolicyCall) Return(arg0 error) *MockS3ClientSetBucketPolicyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockS3ClientSetBucketPolicyCall) Do(f func(context.Context, string, string, string) error) *MockS3ClientSetBucketPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockS3ClientSetBucketPolicyCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockS3ClientSetBucketPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
