kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "linode-cosi-driver.rbacName" . }}
  labels:
    {{- include "linode-cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - objectstorage.k8s.io # COSI resources are grouped here
    resources: # we do not add bucketclasses here, as those are managed by COSI Controller
      - buckets
      - bucketclaims
      - bucketaccesses
      - bucketaccessclasses
      - buckets/status
      - bucketaccesses/status
      - bucketclaims/status
      - bucketaccessclasses/status
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases # lease is created during leader election process by COSI Provisioner Sidecar
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch
  - apiGroups:
      - "" # default API group
    resources:
      - events # events are emmited from COSI Provisioner Sidecar
      - secrets # secrets are created by COSI Provisioner Sidecar as a part of access granting
    verbs: # CRUD
      - create
      - get
      - update
      - delete
