kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "linode-cosi-driver.rbacName" . }}
  labels:
    {{- include "linode-cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "linode-cosi-driver.rbacName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "linode-cosi-driver.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
