apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linode-cosi-driver.name" . }}
  labels:
    {{- include "linode-cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $val := .Values.driver.otelConfig }}
  {{- $key | nindent 2 }}: {{ quote $val }}
  {{- end }}
  COSI_LINODE_WITH_O11Y: {{ quote (include "linode-cosi-driver.observability" .) }}
