apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linode-cosi-driver.name" . }}
  labels:
    {{- include "linode-cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if ne (len (keys .Values.driver.otelConfig)) 0 }}
  {{- range $key, $val := .Values.driver.otelConfig }}
  {{- $key | nindent 2 }}: {{ quote $val }}
  {{- end }}
  {{- else }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_TIMEOUT: "10000"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  {{- end }}
  COSI_LINODE_WITH_O11Y: {{ quote (include "linode-cosi-driver.observability" .) }}
