apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "linode-cosi-driver.rbacName" . }}
  labels:
    {{- include "linode-cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
