# This workflow is used to declaratively sync labels.
# It is supposed to be run on push to main.

name: Sync labels

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shanduur/declarative-labels-sync-action@main
        with:
          owner: linode
          repository: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
