# This workflow runs release please GitHub action. It is supposed to be run on each
# push to main branch.

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }} # need to use separate PAT from GITHUB_TOKEN, so new actions can be triggered
          config-file: .github/release-please-config.json
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - run: |
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/release-gen.sh shanduur
