# This workflow run linters on kubernetes resources.
# It is supposed to be run on each push to main branch, as well as for each push in pull request.

name: K8s Linters

on:
  pull_request:
    branches: [ '*' ]
    paths:
      - 'helm/**'

jobs:
  linters:
    name: Lint Kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: helm/
          config: helm/.kube-linter.yaml
