# This workflow is used to run all necessary actions after the release.
# This should include building and pushing the image.
# It is supposed to be run on each new release.

name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: docker.io

jobs:
  docker:
    name: Build dev image and run scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}
          target: runtime
