name: autopilot

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      contains(github.event.pull_request.labels.*.name, 'area/dependency') &&
      !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&
      github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
