name: k8s-linters

on:
  merge_group:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - "main"

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true
      - uses: helm/chart-testing-action@v2
      - run: |
          ct lint --target-branch ${{ github.event.repository.default_branch }}

  kube-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache: false
      - run: |
          make lint-manifests
      - run: |
          make \
            generate-docs \
            generate-schemas \
            diff
