name: labels

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shanduur/declarative-labels-sync-action@main
        with:
          owner: linode
          repository: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
