name: linters

on:
  merge_group:
  pull_request:
    branches: [ '*' ]
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install_args: go golangci-lint
      - run: |
          mise run lint

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          make hadolint
