name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "main"

permissions:
  contents: write
  packages: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - id: semver_parser
        uses: release-kit/semver@v2
        with:
          string: ${{ github.ref_name }}
      - id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeTypes: ""
          excludeScopes: ""
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: ${{ steps.semver_parser.outputs.prerelease == '' }}
          prerelease: ${{ steps.semver_parser.outputs.prerelease != '' }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/linode/linode-cosi-driver:${{ github.ref_name }}
