name: tests

on:
  merge_group:
  pull_request_target:
    branches: [ '*' ]
  push:
    branches:
      - "main"

concurrency:
  group: e2e-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  integration:
    environment: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) && 'prod-external' || 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install_args: go
      - env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          export LINODE_TOKEN=${LINODE_TOKEN:?Token not set or empty}
          mise run test-integration

  e2e:
    environment: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) && 'prod-external' || 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install_args: go kubectl helm kind ctlptl tilt github:kyverno/chainsaw
      - env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          mise run test-e2e
